<s_exp> ::= "(" <oper> ") " <s_exp> | <empty>
<arg> ::= <var> | <liter> | "(" <oper> ")"
<var> ::= <name>
<name> ::= <let> | <name_extr>
<name_extr> ::= <let> <name_extr> | <num> <name_extr> | <empty>
<let> ::= [a-z]
<num> ::= [0-9]
<liter> ::= <sign> <nums> | "\"" <str> "\"" | "'" <char> "'" | "PRAVDA" | "LOZH"
<char> ::= [a-z] | [0-9]
<sign> ::= <empty> | "+" | "-"
<nums> ::= <num> <nums_extr> 
<nums_extr> ::= <num> <num_extr> | "." <d_num> | <empty>
<d_num> ::= <num> <d_num_extr>
<d_num_extr> ::= <num> <d_num_extr> | <empty>
<str> ::= <char> <str_extr>
<str_extr> ::= <char> <str_extr> | <empty>
<oper> ::= <easy_oper> | <hard_oper> | <func> | <car> | <cdr> /*| <empty> */
<easy_oper> ::= <simple_oper> | <cond_oper>
<argf> ::= <var> | <sign> <num> | "(" <oper> ")"
<simple_oper> ::= <simple> ( " " <argf> )+
<cond_oper> ::= <cond> ( " " <argf> )+
<simple> ::= "+" | "-" | "*" | "/" | "max" | "min"
<cond> ::= "takzhe" | "libo" | "=" | "/=" | ">" | "<" | ">=" | "<="
<hard_oper> ::= <loop_for> | <loop> | <if> | <write> | <read> | <mod> | <not> | <incf> | <decf> | <fact> | <setf> | <func_call>
<loop_for> ::= "idi_poka " <var> " ne_stanet " <num> <s_exp>
<loop> ::= "zhivi " <s_exp> "(umri_kogda (" <cond_oper> "))"
<if> ::= "esli (" <cond_oper> ") (" <oper> ") " <s_exp>
<func> ::= "func " <name> " (" <params> ") (" <s_exp> ") (" <return> ")"
<params> ::= <var> <params_extr> | <empty>
<params_extr> ::= " " <var> <params_extr> | <empty>
<write> ::= "napishi " <arg>
<read> ::= "sprosi " <var>
<mod> ::= "mod " <argf> " " <argf>
<not> ::= "ne " <arg>
<fact> ::= "! " <argf>
<incf> ::= "pribav " <argf> ( " " <argf>)?
<decf> ::= "ubav " <argf> ( " " <argf>)?
<return> ::= "verni " <arg>
<setf> ::= "tovarisch " <var> " " <arg>
<func_call> ::= <var> <params>
<empty> ::= " "